### PR TITLE
fix: readme img urls, new rating badge

### PR DESCRIPTION
**Pull request by renatocfrancisco**
- fixed the readme images, the url was the github link, not the actual image.
- deleted the "trending monthly badge because it was not working.
- added a new badge for vscode marketplace rating

### CODE REVIEW

**Comment by renatocfrancisco** [comment]
i am learning about the "conventional commits". it's tough sometimes to decide.

**Comment by antfu** [comment]
Thanks for the PR. However, the absolute URL is required since the readme is also been used for VS Code marketplace.

**Comment by renatocfrancisco** [comment]
but the logo and the preview are not working in either website. whatever.

**Comment by antfu** [comment]
Yeah I fixed it in https://github.com/antfu/vscode-iconify/commit/72e79181471effea383dfabc6d81b6974fe6460c

**Pull request closed without merging**
